version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    container_name: boilerplate-nestjs-api-db
    restart: always
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
      - ./.docker/postgres:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=boilerplate
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
 

    
